### ISSUE TITLE
reVC crashes after the 2nd alt-tabbing

### ISSUE THREAD

**Issue by VitalRus95** [user-grinch/ImGuiRedux#11]
I checked multiple times with CLEO Redux on and off, with and without every of the plugins and managed to find out that, unfortunately, with ImGui plugin reVC crashes. You can switch to another window and back again once, but on the **second** attempt to return to the game window it crashes, leaving no trace in the log or any other error message.

The crash is **not** present when the game is windowed or when the plugin is deleted.

**Comment by user-grinch** [comment]
I'll need to check it out myself (Probably sometime after June, entrance exams)

**Comment by VitalRus95** [comment]
Sure, that's not a serious issue for me now. Good luck with the exams!

**Comment by user-grinch** [comment]
Closing this, since reVC is dead.
