### ISSUE TITLE
Provide C++ interface

### ISSUE THREAD

**Issue by XMDS** [user-grinch/ImGuiRedux#18]
I want to use C++ code to use imgui in the GTA game. I know you have done a lot of work to dock imgui in GTA, but I hope that for compatibility reasons, it will be better to use the same project implementation.  Therefore, it would be better if you can provide dynamic libraries or compilable static libraries. You can even upload them in pluginsdk (based on the GTAimgui library of the SDK)

**Comment by user-grinch** [comment]
I did a prototype a few years ago. There are some challenges to overcome, but having a global ImGui hook would be neat indeed.  

Although, I'm not sure if exposing ImGuiRedux APIs to C++ would be a good choice. The APIs are limited in their functionality due to CLEO limitations.
