### ISSUE TITLE
please release as zip archive

### ISSUE THREAD

**Issue by x87** [user-grinch/ImGuiRedux#3]
I'm downloading ImGuiRedux with the CLEO Redux installer (see https://github.com/cleolibrary/CLEO-Redux/issues/37) and unzip the archive using Windows methods. It does not support 7z and I would like to minimize the dependencies.

see https://github.com/ThirteenAG/zip-release

Also if possible can you make an extra tag named `x86-latest` which will be a duplicate of the most recent version. ThirteenAG made it for Ultimate ASI Loader and it's convenient to have as a permanent link 
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/tag/x64-latest

**Comment by user-grinch** [comment]
Sure, I'll work on it.

**Comment by x87** [comment]
yes, it can be named Win32-latest or x86-latest. If we ever get the plugin version for the DE (x64) we can create another release tag x64-latest
