### ISSUE TITLE
Colour picker resets

### ISSUE THREAD

**Issue by VitalRus95** [user-grinch/ImGuiRedux#6]
A small but unpleasant issue with colour picker resetting to black. And it seems the same can happen to some sliders. For instance, I have several sliders to set the player's position, and the user can choose to use input instead for greater precision, and when I set a value via input and then return to sliders mode again, the value keeps resetting every time I move a slider.

**Comment by user-grinch** [comment]
Are you using same names for those widgets? 

Try with different names ( Widget1##ColorPicker, Widget1##Slider should also do )

**Comment by VitalRus95** [comment]
Hm, no, I have only one ColorPicker with a unique name. I tried adding `##Colpicker` at the end of the name, but it didn't help. I've also created an ImGui menu with Color Picker being the only widget, and the issue persists. I remember well that it wasn't present earlier, otherwise I wouldn't have used the widget in my HUD mod.
